[project]
name = "essay-stream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "coqui-tts>=0.24.3",
    "langchain>=0.3.20",
    "langchain-community>=0.3.19",
    "nltk>=3.9.1",
    "pymupdf>=1.25.4",
]
